import mysql.connector
import datetime
name=input()
email=input()
phoneno=input()
amount=float(input())
aad=int(input())
gen=input()
password=input()
now=datetime.datetime.now()
date=now.strftime("%d-%m-%y")
time=now.strftime("%H:%M:%S")
mydb=mysql.connector.connect(host="localhost",user="root",password="akash",database="ticket")
mycursor=mydb.cursor()
print("connection established")
sqlform="insert into counter(name,E_mail,Phone_no,Amount,Date,Time,Aadhar_no,Gender,Password) values('{}','{}','{}',{},'{}','{}',{},'{}','{}')".format(name,email,phoneno,amount,date,time,aad,gen,password)
mycursor.execute(sqlform)
mydb.commit()
tname=name+str(aad)
mycursor.execute("CREATE TABLE {}(date VARCHAR(8),time VARCHAR(8),credit int,debit int)".format(tname))
print("table created")